-- ════════════════════════════════════════════════════════════════════════════
-- 002 — THE TELEMETRY SIDE (OLAP-shaped)
-- ════════════════════════════════════════════════════════════════════════════
--
-- Huge, append-only, never updated, and never read one row at a time. Every
-- real query is "aggregate across millions of rows in a time window".
--
-- A security camera tape, not a filing cabinet. Nobody watches one frame; you
-- ask how many people came through between 2pm and 3pm.
--
-- That difference — not taste — is why this file partitions, uses BRIN instead
-- of B-tree on time, stores previews instead of full text, and maintains a
-- pre-aggregated rollup.
-- ════════════════════════════════════════════════════════════════════════════

CREATE TYPE inference_status AS ENUM ('ok', 'error', 'cancelled');

CREATE TYPE inference_error_type AS ENUM (
  'rate_limit', 'timeout', 'auth', 'content_filter', 'context_length',
  'invalid_request', 'server_error', 'network', 'unknown'
);

CREATE TYPE capture_layer AS ENUM ('manual', 'proxy', 'loader');

-- ────────────────────────────────────────────────────────────────────────────
-- inference_events — one row per model call
-- ────────────────────────────────────────────────────────────────────────────
CREATE TABLE inference_events (
  -- ── Identity ──────────────────────────────────────────────────────────────
  -- Generated by the SDK, not the database, because it must exist before the
  -- row does: it is the idempotency key that makes at-least-once delivery safe.
  event_id          uuid        NOT NULL,

  -- Partition key. Set from the event's own start time, never now(), so that a
  -- retried batch lands in the same partition with the same key and the
  -- ON CONFLICT below actually matches. If this were now(), a duplicate
  -- delivered a second later would insert twice and quietly double the traffic
  -- on every chart.
  created_at        timestamptz NOT NULL,

  -- ── Correlation ───────────────────────────────────────────────────────────
  -- ON DELETE SET NULL, deliberately not CASCADE.
  --
  -- Deleting a conversation is a product action; it should not silently erase
  -- the operational record that the system served 400 requests that hour. The
  -- telemetry row survives, detached and already carrying only a truncated
  -- preview rather than the full text.
  --
  -- The counter-argument is GDPR: an erasure request must remove the content,
  -- and a preview is still content. That is handled by redact_conversation()
  -- in 004, which nulls the previews without destroying the metrics. Erasure
  -- and amnesia are different requirements and this schema treats them so.
  conversation_id   uuid REFERENCES conversations(id) ON DELETE SET NULL,
  message_id        uuid REFERENCES messages(id)      ON DELETE SET NULL,
  session_id        text,
  user_id           text,

  -- ── What was called ───────────────────────────────────────────────────────
  -- provider and model are denormalised strings rather than FKs to a lookup
  -- table. They are low-cardinality and on the hot path of every aggregate
  -- query; a join here would buy referential tidiness at the cost of the one
  -- thing this table exists to do quickly. New models must also be able to
  -- appear without a migration.
  provider          text NOT NULL,
  model             text NOT NULL,
  operation         text NOT NULL DEFAULT 'chat',
  streamed          boolean NOT NULL DEFAULT false,
  captured_by       capture_layer NOT NULL DEFAULT 'proxy',

  -- ── Outcome ───────────────────────────────────────────────────────────────
  status            inference_status NOT NULL,
  finish_reason     text,
  error_type        inference_error_type,
  error_message     text,

  -- ── Timing ────────────────────────────────────────────────────────────────
  latency_ms        integer NOT NULL,
  -- Null for non-streamed calls. Total latency describes the request; TTFT
  -- describes what the user actually experienced.
  ttft_ms           integer,

  -- ── Usage ─────────────────────────────────────────────────────────────────
  -- Nullable, never defaulted to 0. Usage is genuinely sometimes unavailable
  -- (a stream that died before the usage frame). Storing 0 would be a lie that
  -- silently deflates every cost and token aggregate downstream.
  input_tokens      integer,
  output_tokens     integer,
  cache_read_tokens integer,
  cache_write_tokens integer,

  -- Frozen at ingestion, with the price list that produced it.
  --
  -- Computing cost at query time would mean a vendor price change silently
  -- rewrites last year's spend. Receipts do not change when the shop changes
  -- its prices, and neither should these.
  cost_usd          numeric(14, 8),
  pricing_version   text,

  -- ── Request shape ─────────────────────────────────────────────────────────
  temperature       real,
  max_tokens        integer,
  message_count     integer,

  -- ── Payload previews ──────────────────────────────────────────────────────
  -- Truncated on purpose. Full text lives in messages; duplicating it here
  -- would widen the table that every dashboard query scans, for no analytical
  -- benefit whatsoever.
  input_preview     text,
  output_preview    text,
  redaction_hits    smallint NOT NULL DEFAULT 0,

  -- ── Provenance ────────────────────────────────────────────────────────────
  -- Two timestamps, on purpose.
  --   client_ts   — when the SDK observed the call (client clock)
  --   ingested_at — when the server received it (server clock)
  --
  -- Their difference is pipeline lag: the metric that says the system is
  -- falling behind before users notice. It also exposes clock skew — if
  -- client_ts is in the future, that client's clock is wrong and the server's
  -- timestamp is the one to order by.
  client_ts         timestamptz NOT NULL,
  ingested_at       timestamptz NOT NULL DEFAULT now(),
  sdk_version       text,
  schema_version    smallint NOT NULL DEFAULT 1,

  -- The misc drawer. Provider-specific extras that do not deserve a column yet.
  -- Rule: if you find yourself querying inside it, promote the field. No GIN
  -- index until a real query needs one — an unused GIN index is pure write cost.
  attributes        jsonb NOT NULL DEFAULT '{}'::jsonb,

  -- A partitioned table's primary key must contain the partition key.
  PRIMARY KEY (event_id, created_at)
) PARTITION BY RANGE (created_at);

-- ── Indexes ─────────────────────────────────────────────────────────────────

-- Time-range scans: "the last 24 hours", which is every dashboard query.
--
-- BRIN, not B-tree. The table is append-only and physically ordered by time,
-- which is exactly BRIN's assumption. It stores min/max per block range rather
-- than an entry per row: kilobytes where a B-tree over 10M rows is hundreds of
-- megabytes, and correspondingly near-free to maintain on insert.
CREATE INDEX inference_events_time_brin
  ON inference_events USING brin (created_at) WITH (pages_per_range = 32);

-- The drill-down: "this call was slow — what was the user asking?"
-- Reading the graph upwards is the entire point of the product, so this one
-- earns a real B-tree.
CREATE INDEX inference_events_conv_idx
  ON inference_events (conversation_id, created_at DESC)
  WHERE conversation_id IS NOT NULL;

-- The error panel. Partial: failures are a small fraction of rows, so this
-- index is a small fraction of the size and the scan touches only what matters.
CREATE INDEX inference_events_errors_idx
  ON inference_events (created_at DESC, error_type)
  WHERE status <> 'ok';

-- ────────────────────────────────────────────────────────────────────────────
-- Partitions
-- ────────────────────────────────────────────────────────────────────────────
--
-- One physical table per month, presented by Postgres as one logical table.
-- Two payoffs:
--
--   1. Pruning — "last 24 hours" touches only the current month's partition and
--      the planner never looks at the rest.
--   2. Retention — dropping September is DROP TABLE, which is instant. Deleting
--      10M rows with DELETE takes minutes, bloats the heap, and holds locks.
--
-- One box of receipts per month, not one giant box.
CREATE OR REPLACE FUNCTION ensure_events_partition(target date)
RETURNS text AS $$
DECLARE
  start_date date := date_trunc('month', target)::date;
  end_date   date := (date_trunc('month', target) + interval '1 month')::date;
  part_name  text := format('inference_events_%s', to_char(start_date, 'YYYY_MM'));
BEGIN
  IF to_regclass(part_name) IS NULL THEN
    EXECUTE format(
      'CREATE TABLE %I PARTITION OF inference_events FOR VALUES FROM (%L) TO (%L)',
      part_name, start_date, end_date
    );
  END IF;
  RETURN part_name;
END
$$ LANGUAGE plpgsql;

-- Current and next month, so an insert at 23:59 on the last of the month does
-- not fail for want of a partition. Production would run this from a scheduled
-- job; the migration runner calls it on every startup, which is cheap and
-- idempotent and removes an entire class of 3am incident.
SELECT ensure_events_partition(CURRENT_DATE);
SELECT ensure_events_partition((CURRENT_DATE + interval '1 month')::date);

-- A catch-all for anything outside the known range. Without it, a client with a
-- badly wrong clock causes an insert error that fails the whole batch. With it,
-- the row lands somewhere inspectable and the batch succeeds.
CREATE TABLE inference_events_overflow PARTITION OF inference_events DEFAULT;
